# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Austin Smith
email: asmith29@ufl.edu
description: > # this means to ignore newlines until "baseurl:"
  Hey there, I'm Austin Smith. I am a Computer Science student at the
  University of Florida who decided to start a personal blog for some
  reason.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://amsmith.me" # the base hostname & protocol for your site
twitter_username: _austinsmitty
github_username: AustinSmith29 

# Build settings
markdown: kramdown

